// js/data.js
window.createDim = (M, L, T, I=0, K=0, mol=0) => ({ M, L, T, I, K, mol });

window.dimDict = {
    'm': { name: 'Mass', concept: ['Fundamental'], breakdown: ['[M]'], units: ['kg', 'g'], app: 'Inertia modeling', chapter: 'mechanics', diff: 'easy', mistake: 'Confusing mass with weight (a force).', jeeTip: 'Always standardise to kg in SI calculations.', ...createDim(1, 0, 0) },
    's': { name: 'Displacement', concept: ['Fundamental'], breakdown: ['[L]'], units: ['m', 'cm'], app: 'Trajectory planning', chapter: 'mechanics', diff: 'easy', mistake: 'Using path length instead of shortest distance.', jeeTip: 'Displacement can be negative; distance cannot.', ...createDim(0, 1, 0) },
    'l': { name: 'Length', concept: ['Fundamental'], breakdown: ['[L]'], units: ['m', 'cm'], app: 'Structural engineering', chapter: 'mechanics', diff: 'easy', mistake: 'Forgetting to convert cm to m.', jeeTip: 'Dimensional analysis treats all lengths (radius, height, breadth) as [L].', ...createDim(0, 1, 0) },
    'd': { name: 'Distance', concept: ['Fundamental'], breakdown: ['[L]'], units: ['m', 'cm'], app: 'Kinematics', chapter: 'mechanics', diff: 'easy', mistake: 'Using path length instead of shortest distance.', jeeTip: 'Same dimensional treatment as displacement.', ...createDim(0, 1, 0) },
    't': { name: 'Time', concept: ['Fundamental'], breakdown: ['[T]'], units: ['s', 'hr'], app: 'Reaction kinetics', chapter: 'mechanics', diff: 'easy', mistake: 'Using minutes or hours directly in SI equations.', jeeTip: 'Time period of a pendulum T ∝ √(l/g) is a classic derivation.', ...createDim(0, 0, 1) },
    'A': { name: 'Area', concept: ['Length', 'Length'], op: '×', breakdown: ['[L]', '[L]'], units: ['m²'], app: 'Aerodynamics', chapter: 'mechanics', diff: 'easy', mistake: 'Squaring the unit but forgetting to square the conversion factor.', jeeTip: 'Used frequently in flux calculations and pressure.', ...createDim(0, 2, 0) },
    'Vol': { name: 'Volume', concept: ['Area', 'Length'], op: '×', breakdown: ['[L²]', '[L]'], units: ['m³'], app: 'Fluid capacity', chapter: 'mechanics', diff: 'easy', mistake: 'Confusing Liters with SI units. 1 m³ = 1000 L.', jeeTip: 'Vital for density and buoyancy dimensional checks.', ...createDim(0, 3, 0) },
    'v': { name: 'Velocity', concept: ['Displacement', 'Time'], op: '/', breakdown: ['[L]', '[T]'], units: ['m/s'], app: 'Orbital mechanics', chapter: 'mechanics', diff: 'easy', mistake: 'Confusing average speed with average velocity.', jeeTip: 'All velocities (drift, escape, terminal) share [LT⁻¹].', ...createDim(0, 1, -1) },
    'u': { name: 'Initial Velocity', concept: ['Displacement', 'Time'], op: '/', breakdown: ['[L]', '[T]'], units: ['m/s'], app: 'Launch velocities', chapter: 'mechanics', diff: 'easy', mistake: 'Treating as different from final velocity.', jeeTip: 'Dimensionally identical to final velocity.', ...createDim(0, 1, -1) },
    'a': { name: 'Acceleration', concept: ['Velocity', 'Time'], op: '/', breakdown: ['[LT⁻¹]', '[T]'], units: ['m/s²'], app: 'G-force tolerances', chapter: 'mechanics', diff: 'easy', mistake: 'Forgetting the squared time unit.', jeeTip: 'Centripetal and tangential acceleration have identical dimensions.', ...createDim(0, 1, -2) },
    'g': { name: 'Gravity Accel', concept: ['Velocity', 'Time'], op: '/', breakdown: ['[LT⁻¹]', '[T]'], units: ['m/s²'], app: 'Freefall calculations', chapter: 'mechanics', diff: 'easy', mistake: 'Treating as a fundamental constant.', jeeTip: 'Treat exactly like normal acceleration.', ...createDim(0, 1, -2) },
    'F': { name: 'Force', concept: ['Mass', 'Acceleration'], op: '×', breakdown: ['[M]', '[LT⁻²]'], units: ['Newton (N)'], app: 'Rocket thrust', chapter: 'mechanics', diff: 'medium', mistake: 'Confusing Force [MLT⁻²] with Energy [ML²T⁻²].', jeeTip: 'Memorize [MLT⁻²]. Nearly 50% of derivations build off Force.', ...createDim(1, 1, -2) },
    'p': { name: 'Momentum', concept: ['Mass', 'Velocity'], op: '×', breakdown: ['[M]', '[LT⁻¹]'], units: ['kg·m/s'], app: 'Collision physics', chapter: 'mechanics', diff: 'medium', mistake: 'Thinking momentum and kinetic energy have the same relation without squaring v.', jeeTip: 'Momentum and Impulse [MLT⁻¹] share identical dimensions.', ...createDim(1, 1, -1) },
    'J': { name: 'Impulse', concept: ['Force', 'Time'], op: '×', breakdown: ['[MLT⁻²]', '[T]'], units: ['N·s'], app: 'Airbag design', chapter: 'mechanics', diff: 'medium', mistake: 'Confusing it with work (Force × Distance).', jeeTip: 'J = Δp. Useful for quickly replacing momentum in equations.', ...createDim(1, 1, -1) },
    'Tau': { name: 'Torque', concept: ['Force', 'Distance'], op: '×', breakdown: ['[MLT⁻²]', '[L]'], units: ['N·m'], app: 'Engine output', chapter: 'mechanics', diff: 'medium', mistake: 'Treating Torque as Energy. While both are [ML²T⁻²], Torque is a vector cross product.', jeeTip: 'Torque and Work share identical dimensions. A common trap question.', ...createDim(1, 2, -2) },
    'L_ang': { name: 'Angular Momentum', concept: ['Momentum', 'Distance'], op: '×', breakdown: ['[MLT⁻¹]', '[L]'], units: ['kg·m²/s'], app: 'Gyroscopes', chapter: 'mechanics', diff: 'hard', mistake: 'Forgetting the r factor. It is mvr, not just mv.', jeeTip: 'Angular Momentum has the exact same dimensions as Planck\'s Constant (h).', ...createDim(1, 2, -1) },
    'MoI': { name: 'Moment of Inertia', concept: ['Mass', 'Distance²'], op: '×', breakdown: ['[M]', '[L²]'], units: ['kg·m²'], app: 'Flywheels', chapter: 'mechanics', diff: 'medium', mistake: 'Adding linear mass to rotational mass equations blindly.', jeeTip: 'Acts as the rotational equivalent of mass in [ML²T⁻²] energy equations.', ...createDim(1, 2, 0) },
    'W': { name: 'Work', concept: ['Force', 'Displacement'], op: '×', breakdown: ['[MLT⁻²]', '[L]'], units: ['Joule (J)'], app: 'Energy expenditure', chapter: 'mechanics', diff: 'medium', mistake: 'Forgetting that Work requires displacement in the direction of force.', jeeTip: 'Work, Energy, and Torque all share [ML²T⁻²].', ...createDim(1, 2, -2) },
    'E': { name: 'Energy', concept: ['Force', 'Displacement'], op: '×', breakdown: ['[MLT⁻²]', '[L]'], units: ['Joule (J)'], app: 'Power grids', chapter: 'mechanics', diff: 'medium', mistake: 'Confusing energy dimensions with power [ML²T⁻³].', jeeTip: 'All forms of energy (Kinetic, Potential, Thermal) share [ML²T⁻²].', ...createDim(1, 2, -2) },
    'KE': { name: 'Kinetic Energy', concept: ['Mass', 'Velocity²'], op: '×', breakdown: ['[M]', '[LT⁻¹]²'], units: ['Joule (J)'], app: 'Ballistics', chapter: 'mechanics', diff: 'medium', mistake: 'Forgetting to square the velocity in manual derivations.', jeeTip: 'Constants like ½ are dimensionless and ignored in analysis.', ...createDim(1, 2, -2) },
    'PE': { name: 'Potential Energy', concept: ['Mass', 'Gravity × Height'], op: '×', breakdown: ['[M]', '[L²T⁻²]'], units: ['Joule (J)'], app: 'Gravitational modeling', chapter: 'mechanics', diff: 'medium', mistake: 'Treating g as dimensionless.', jeeTip: 'Dimensionally identical to Work.', ...createDim(1, 2, -2) },
    'V_g': { name: 'Gravitational Potential', concept: ['Potential Energy', 'Mass'], op: '/', breakdown: ['[ML²T⁻²]', '[M]'], units: ['J/kg'], app: 'Orbital mechanics', chapter: 'mechanics', diff: 'hard', mistake: 'Confusing potential with potential energy.', jeeTip: 'Gravitational Potential is Energy per unit Mass. [L²T⁻²].', ...createDim(0, 2, -2) },
    'P': { name: 'Power', concept: ['Work', 'Time'], op: '/', breakdown: ['[ML²T⁻²]', '[T]'], units: ['Watt (W)'], app: 'Motor sizing', chapter: 'mechanics', diff: 'medium', mistake: 'Confusing Watts (Power) with Joules (Energy).', jeeTip: 'P = Fv. Multiplying Force [MLT⁻²] by Velocity [LT⁻¹] quickly gives [ML²T⁻³].', ...createDim(1, 2, -3) },
    'Pr': { name: 'Pressure', concept: ['Force', 'Area'], op: '/', breakdown: ['[MLT⁻²]', '[L²]'], units: ['Pascal (Pa)'], app: 'Hydraulics', chapter: 'mechanics', diff: 'medium', mistake: 'Confusing Pressure [ML⁻¹T⁻²] with Force [MLT⁻²].', jeeTip: 'Pressure, Stress, and Modulus of Elasticity share identical dimensions.', ...createDim(1, -1, -2) },
    'Stress': { name: 'Stress', concept: ['Force', 'Area'], op: '/', breakdown: ['[MLT⁻²]', '[L²]'], units: ['Pascal (Pa)'], app: 'Material failure', chapter: 'mechanics', diff: 'medium', mistake: 'Assuming stress is a force. It is force per unit area.', jeeTip: 'Often equated directly to Pressure in Buckingham Pi problems.', ...createDim(1, -1, -2) },
    'Strain': { name: 'Strain', concept: ['Length', 'Length'], op: '/', breakdown: ['[L]', '[L]'], units: ['Dimensionless'], app: 'Deformation', chapter: 'mechanics', diff: 'easy', mistake: 'Assigning [L] to strain. It is a ratio.', jeeTip: 'Trigonometric functions and Strain are both completely dimensionless.', ...createDim(0, 0, 0) },
    'Y': { name: 'Young Modulus', concept: ['Stress', 'Strain'], op: '/', breakdown: ['[ML⁻¹T⁻²]', '[1]'], units: ['Pascal (Pa)'], app: 'Bridge design', chapter: 'mechanics', diff: 'hard', mistake: 'Trying to derive it without realizing Strain is dimensionless.', jeeTip: 'Since strain is 1, Young\'s Modulus has the exact same dimensions as Stress/Pressure.', ...createDim(1, -1, -2) },
    'rho': { name: 'Density', concept: ['Mass', 'Volume'], op: '/', breakdown: ['[M]', '[L³]'], units: ['kg/m³'], app: 'Buoyancy', chapter: 'mechanics', diff: 'medium', mistake: 'Mixing up density [ML⁻³] with specific gravity (dimensionless).', jeeTip: 'Crucial for fluid mechanics derivations like Bernoulli\'s principle.', ...createDim(1, -3, 0) },
    'mu': { name: 'Viscosity', concept: ['Shear Stress', 'Vel Gradient'], op: '/', breakdown: ['[ML⁻¹T⁻²]', '[T⁻¹]'], units: ['Pa·s'], app: 'Motor oil rating', chapter: 'mechanics', diff: 'hard', mistake: 'Forgetting that velocity gradient is [T⁻¹].', jeeTip: 'Memorize [ML⁻¹T⁻¹]. It appears frequently in Stokes\' Law and Reynolds Number.', ...createDim(1, -1, -1) },
    'ST': { name: 'Surface Tension', concept: ['Force', 'Length'], op: '/', breakdown: ['[MLT⁻²]', '[L]'], units: ['N/m'], app: 'Capillary action', chapter: 'mechanics', diff: 'medium', mistake: 'Confusing it with surface energy. (Actually, Energy/Area gives the same [MT⁻²]).', jeeTip: 'Notice L cancels out entirely. Surface Tension is purely [MT⁻²].', ...createDim(1, 0, -2) },
    'f': { name: 'Frequency', concept: ['Cycles', 'Time'], op: '/', breakdown: ['[1]', '[T]'], units: ['Hertz (Hz)'], app: 'Acoustics', chapter: 'mechanics', diff: 'easy', mistake: 'Adding dimensions to the "cycle" count.', jeeTip: 'Angular frequency (ω) and standard frequency (f) share [T⁻¹].', ...createDim(0, 0, -1) },
    'omega': { name: 'Angular Frequency', concept: ['Angle', 'Time'], op: '/', breakdown: ['[1]', '[T]'], units: ['rad/s'], app: 'Wave mechanics', chapter: 'mechanics', diff: 'medium', mistake: 'Treating radians as [L]. Radian is dimensionless.', jeeTip: 'Dimensionally identical to normal frequency.', ...createDim(0, 0, -1) },
    'alpha': { name: 'Angular Acceleration', concept: ['Angular Velocity', 'Time'], op: '/', breakdown: ['[T⁻¹]', '[T]'], units: ['rad/s²'], app: 'Rotational dynamics', chapter: 'mechanics', diff: 'medium', mistake: 'Including [L] in the formula.', jeeTip: 'Purely [T⁻²].', ...createDim(0, 0, -2) },
    'k_wave': { name: 'Wave Number', concept: ['Angle', 'Length'], op: '/', breakdown: ['[1]', '[L]'], units: ['rad/m'], app: 'Quantum mechanics', chapter: 'mechanics', diff: 'medium', mistake: 'Treating as a dimensionless constant.', jeeTip: 'It is the spatial analog of angular frequency. [L⁻¹].', ...createDim(0, -1, 0) },
    
    'Temp': { name: 'Temperature', concept: ['Fundamental'], breakdown: ['[K]'], units: ['Kelvin (K)'], app: 'Thermal modeling', chapter: 'thermo', diff: 'easy', mistake: 'Treating temperature as an energy.', jeeTip: 'Ensure K (Kelvin) is used in dimensions, not C.', ...createDim(0, 0, 0, 0, 1) },
    'n': { name: 'Amount of Substance', concept: ['Fundamental'], breakdown: ['[mol]'], units: ['Mole'], app: 'Chemical reactions', chapter: 'thermo', diff: 'easy', mistake: 'Forgetting mol in gas equations.', jeeTip: 'A fundamental dimension. Don\'t ignore it in PV=nRT.', ...createDim(0, 0, 0, 0, 0, 1) },
    'HC': { name: 'Heat Capacity', concept: ['Energy', 'Temperature'], op: '/', breakdown: ['[ML²T⁻²]', '[K]'], units: ['J/K'], app: 'HVAC systems', chapter: 'thermo', diff: 'medium', mistake: 'Confusing it with Specific Heat (which divides by Mass).', jeeTip: 'Heat is just Energy. Substitute [ML²T⁻²] directly.', ...createDim(1, 2, -2, 0, -1) },
    'SHC': { name: 'Specific Heat', concept: ['Heat Capacity', 'Mass'], op: '/', breakdown: ['[ML²T⁻²K⁻¹]', '[M]'], units: ['J/(kg·K)'], app: 'Thermodynamics', chapter: 'thermo', diff: 'medium', mistake: 'Forgetting to divide by mass.', jeeTip: 'Note the missing [M] compared to Heat Capacity.', ...createDim(0, 2, -2, 0, -1) },
    'ThermalCond': { name: 'Thermal Conductivity', concept: ['Power', '(Area × TempGrad)'], op: '/', breakdown: ['[ML²T⁻³]', '[L²]×[KL⁻¹]'], units: ['W/(m·K)'], app: 'Insulation', chapter: 'thermo', diff: 'hard', mistake: 'Mishandling the Temperature Gradient ([K]/[L]).', jeeTip: 'Break it down slowly: Power / (Length × Temperature).', ...createDim(1, 1, -3, 0, -1) },
    
    'I': { name: 'Current', concept: ['Fundamental'], breakdown: ['[I]'], units: ['Ampere (A)'], app: 'Circuit design', chapter: 'em', diff: 'easy', mistake: 'Deriving Current from Charge. In the SI system, Current [I] is fundamental.', jeeTip: 'Charge is [IT], not the other way around.', ...createDim(0, 0, 0, 1) },
    'q': { name: 'Charge', concept: ['Current', 'Time'], op: '×', breakdown: ['[I]', '[T]'], units: ['Coulomb (C)'], app: 'Battery limits', chapter: 'em', diff: 'easy', mistake: 'Treating Charge as a fundamental dimension.', jeeTip: 'Always substitute [IT] for charge in electrostatic derivations.', ...createDim(0, 0, 1, 1) },
    'V': { name: 'Voltage', concept: ['Work', 'Charge'], op: '/', breakdown: ['[ML²T⁻²]', '[IT]'], units: ['Volt (V)'], app: 'Power transmission', chapter: 'em', diff: 'medium', mistake: 'Trying to derive V from V=IR without knowing R.', jeeTip: 'Always derive Voltage via Energy/Charge to save time.', ...createDim(1, 2, -3, -1) },
    'R': { name: 'Resistance', concept: ['Voltage', 'Current'], op: '/', breakdown: ['[ML²T⁻³I⁻¹]', '[I]'], units: ['Ohm (Ω)'], app: 'Heating elements', chapter: 'em', diff: 'medium', mistake: 'Dropping the negative signs on the exponents during division.', jeeTip: 'R = [ML²T⁻³I⁻²]. The I⁻² is a dead giveaway for resistance in MCQs.', ...createDim(1, 2, -3, -2) },
    'Resistivity': { name: 'Resistivity', concept: ['Resistance × Area', 'Length'], op: '/', breakdown: ['[ML²T⁻³I⁻²]×[L²]', '[L]'], units: ['Ω·m'], app: 'Material science', chapter: 'em', diff: 'hard', mistake: 'Confusing it with resistance.', jeeTip: 'Notice it is Resistance × Length [L].', ...createDim(1, 3, -3, -2) },
    'Conductivity': { name: 'Conductivity', concept: ['1', 'Resistivity'], op: '/', breakdown: ['[1]', '[ML³T⁻³I⁻²]'], units: ['S/m'], app: 'Semiconductors', chapter: 'em', diff: 'hard', mistake: 'Forgetting to invert all signs.', jeeTip: 'Simply invert Resistivity: [M⁻¹L⁻³T³I²].', ...createDim(-1, -3, 3, 2) },
    'C': { name: 'Capacitance', concept: ['Charge', 'Voltage'], op: '/', breakdown: ['[IT]', '[ML²T⁻³I⁻¹]'], units: ['Farad (F)'], app: 'Signal filtering', chapter: 'em', diff: 'hard', mistake: 'Inverting the division. C = q/V.', jeeTip: 'Capacitance has a negative Mass exponent [M⁻¹]. Very rare!', ...createDim(-1, -2, 4, 2) },
    'E_field': { name: 'Electric Field', concept: ['Force', 'Charge'], op: '/', breakdown: ['[MLT⁻²]', '[IT]'], units: ['V/m'], app: 'Electrostatics', chapter: 'em', diff: 'medium', mistake: 'Confusing with Electric Potential.', jeeTip: 'Easily derived as Voltage / Length.', ...createDim(1, 1, -3, -1) },
    'B': { name: 'Magnetic Field', concept: ['Force', '(Charge × Velocity)'], op: '/', breakdown: ['[MLT⁻²]', '([IT] × [LT⁻¹])'], units: ['Tesla (T)'], app: 'Motors', chapter: 'em', diff: 'hard', mistake: 'Deriving from Biot-Savart instead of F = qvB.', jeeTip: 'Notice Length cancels out. B is purely [MT⁻²I⁻¹].', ...createDim(1, 0, -2, -1) },
    'Flux': { name: 'Magnetic Flux', concept: ['Magnetic Field', 'Area'], op: '×', breakdown: ['[MT⁻²I⁻¹]', '[L²]'], units: ['Weber (Wb)'], app: 'Generators', chapter: 'em', diff: 'hard', mistake: 'Confusing with Magnetic Field.', jeeTip: 'Multiply B by Area [L²].', ...createDim(1, 2, -2, -1) },
    'Ind': { name: 'Inductance', concept: ['Magnetic Flux', 'Current'], op: '/', breakdown: ['[ML²T⁻²I⁻¹]', '[I]'], units: ['Henry (H)'], app: 'Transformers', chapter: 'em', diff: 'jee-advanced', mistake: 'Messing up the I exponents.', jeeTip: 'Inductance is purely [ML²T⁻²I⁻²].', ...createDim(1, 2, -2, -2) },
    
    'h': { name: 'Planck Constant', concept: ['Energy', 'Frequency'], op: '/', breakdown: ['[ML²T⁻²]', '[T⁻¹]'], units: ['J·s'], app: 'Quantum mechanics', chapter: 'modern', diff: 'jee-advanced', mistake: 'Confusing h with ħ.', jeeTip: 'Planck\'s Constant shares identical dimensions with Angular Momentum.', ...createDim(1, 2, -1) },
    'G': { name: 'Gravitational Constant', concept: ['(Force × Dist²)', 'Mass²'], op: '/', breakdown: ['[ML³T⁻²]', '[M²]'], units: ['N·m²/kg²'], app: 'Astrophysics', chapter: 'modern', diff: 'jee-advanced', mistake: 'Forgetting to square the distance or mass.', jeeTip: 'G has a negative mass exponent: [M⁻¹L³T⁻²].', ...createDim(-1, 3, -2) },
    'k': { name: 'Boltzmann Constant', concept: ['Energy', 'Temperature'], op: '/', breakdown: ['[ML²T⁻²]', '[K]'], units: ['J/K'], app: 'Statistical mechanics', chapter: 'modern', diff: 'jee-advanced', mistake: 'Treating as a dimensionless constant.', jeeTip: 'Dimensionally identical to Heat Capacity & Entropy.', ...createDim(1, 2, -2, 0, -1) },
    'R_gas': { name: 'Gas Constant', concept: ['Energy', '(Temp × Mol)'], op: '/', breakdown: ['[ML²T⁻²]', '([K] × [mol])'], units: ['J/(mol·K)'], app: 'Ideal gas law', chapter: 'modern', diff: 'jee-advanced', mistake: 'Forgetting [mol].', jeeTip: 'Used in PV = nRT.', ...createDim(1, 2, -2, 0, -1, -1) },
    'N_A': { name: 'Avogadro Number', concept: ['Particles', 'Mole'], op: '/', breakdown: ['[1]', '[mol]'], units: ['mol⁻¹'], app: 'Chemistry', chapter: 'modern', diff: 'medium', mistake: 'Assuming it is dimensionless.', jeeTip: 'Has dimension [mol⁻¹].', ...createDim(0, 0, 0, 0, 0, -1) },
    'eps0': { name: 'Permittivity (ε₀)', concept: ['Charge²', '(Force × Dist²)'], op: '/', breakdown: ['[IT]²', '[ML³T⁻²]'], units: ['F/m'], app: 'Dielectrics', chapter: 'modern', diff: 'jee-advanced', mistake: 'Using charge [q] instead of [IT] during derivation.', jeeTip: 'Speed of light c = 1/√(μ₀ε₀). Frequent dimensional check.', ...createDim(-1, -3, 4, 2) },
    'mu0': { name: 'Permeability (μ₀)', concept: ['Magnetic Field × Dist', 'Current'], op: '/', breakdown: ['[MT⁻²I⁻¹] × [L]', '[I]'], units: ['H/m'], app: 'Electromagnetism', chapter: 'modern', diff: 'jee-advanced', mistake: 'Mixing up with permittivity.', jeeTip: 'Used in c = 1/√(μ₀ε₀).', ...createDim(1, 1, -2, -2) },
    'sigma': { name: 'Stefan-Boltzmann Constant', concept: ['Intensity', 'Temperature⁴'], op: '/', breakdown: ['[MT⁻³]', '[K⁴]'], units: ['W/(m²·K⁴)'], app: 'Blackbody radiation', chapter: 'modern', diff: 'jee-advanced', mistake: 'Forgetting Temperature is to the 4th power.', jeeTip: 'Power per unit Area per K⁴.', ...createDim(1, 0, -3, 0, -4) },
    'b_wien': { name: 'Wien Constant', concept: ['Length', 'Temperature'], op: '×', breakdown: ['[L]', '[K]'], units: ['m·K'], app: 'Astrophysics', chapter: 'modern', diff: 'hard', mistake: 'Using division instead of multiplication.', jeeTip: 'λ_max × T = b.', ...createDim(0, 1, 0, 0, 1) }
};

for(let key in window.dimDict) {
    if(!window.dimDict[key].mistake) window.dimDict[key].mistake = "Misaligning fundamental dimension substitutions.";
    if(!window.dimDict[key].jeeTip) window.dimDict[key].jeeTip = "Ensure you resolve all fractions before finalising exponents.";
}

window.aliasMap = { 'm1': 'm', 'm2': 'm', 'r': 'd', 'x': 's', 'y': 's', 'P': 'Pr', 'T': 'Temp', 'Rg': 'R_gas', 'Rgas': 'R_gas', 'c': 'v' };

window.knownPiGroups = {
    "d,mu,rho,v": "Re = ρvd / μ  (Reynolds Number)",
    "g,l,t": "π = t√(g/l)  (Pendulum Equation)",
    "a,f,rho,v": "Cd = F / (ρAv²)  (Drag Coefficient)",
    "g,h,v": "Fr = v / √(gh)  (Froude Number)"
};
